apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-user-profile
  labels:
    app: s-u-p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-u-p
  template:
    metadata:
      labels:
        app: s-u-p
    spec:
      containers:
        - name: nginx
          image: mdsahiloss/simple-user-profile-page:latest
          ports:
            - containerPort: 3000
